### ISSUE TITLE
那这样抄作业不是很爽

### ISSUE THREAD

**Issue by SionFu** [youngon-cn/Homework#19]

**Comment by F-loat** [comment]
代码的事，是不是抄的很容易看出来的，愿意学的人自然不会去抄。有限度的参考其他人比较好的写法还是鼓励的。

主要的问题还是在于初学者不太熟悉 git，也不懂使用 github 这个平台的益处。

**Comment by NoBey** [comment]
@SionFu  很多问题本来就是开放性的，同一个问题，同一个思路写出来都不会一样，毕竟大多说时候都是在搬运代码
