### ISSUE TITLE
关于学习

### ISSUE THREAD

**Issue by loo41** [youngon-cn/Homework#21]

**Comment by loo41** [comment]
征求意见，作业没交上来也算了，还没交，作业也不多，上半年的他们三个感觉就是有些浮躁，我只能按照正常的安排来了。 咋办了。。。。

**Comment by NoBey** [comment]
@loo41   有兴趣的你不用着急，没兴趣的你着急没用，单纯技术而言，所以东西资料网上，想学谁也拦不住，能做就是展示技术的魅力，去吸引人来。你可以试试把手里玩的一些东西跟他们聊聊看，也许就会有兴趣了。

**Comment by loo41** [comment]
嗯嗯
