### ISSUE TITLE
关于作业提交

### ISSUE THREAD

**Issue by F-loat** [youngon-cn/Homework#4]
提交作业严禁直接修改master分支，具体流程参见readme，另外在自己账号下建个仓库，熟悉熟悉git的使用。。自己的仓库出了什么问题直接删掉都可以啊

**Comment by F-loat** [comment]
@loo41

**Comment by NoBey** [comment]
fork 到自己仓库玩 有问题再往仓库推

**Comment by NoBey** [comment]
把权限改成只读了，推完之后审核在确认发布就行了

**Comment by F-loat** [comment]
我是觉得那样他们太麻烦，就让他们建分支了，fork之后不论是同步还是删了重来都比分支麻烦不少

**Comment by F-loat** [comment]
其实正常的fork的话，他们一直不同步也行，基本也不会有冲突，但是他们操作起来就总有问题。。

**Comment by NoBey** [comment]
fork 同步的话直接 pull 就行了 有什么麻烦的啊，跟合并分支一样，直接在自己仓库推行了，直接去修改这个仓库到时候人多了更麻烦，

**Comment by F-loat** [comment]
那我要不把这个[fork流程](https://github.com/youngon-cn/Homework/blob/c1774cf23d1477dfbcd33a2025432563df9c57c9/README.md)再加上，让他们自己看看吧先，不觉得我能教会他们合并分支，他们自己试试吧，讲道理两种流程我都写的比较清楚了，这都好长时间了，他们自己不看我也没办法

**Comment by NoBey** [comment]
讲道理, 权限给他调低了, 让他自己想办法提交, 提交不上就没作业, 不用管别的, 有问题不懂可以问, 但是不想办法解决问题就是有问题咯, 我觉得我这个思路好, 合并代码最多就是解决一次冲突, 先把作业流搞清楚, 再说做作业

**Comment by F-loat** [comment]
嗯，readme完了我改改吧再，fork的流程是要更不容易破坏主分支，权限是你刚改过了吧

**Comment by NoBey** [comment]
权限改了
